export default [
  {
    _id: "101",
    quiz: "Q101",
    type: "TF",
    title: "1+1=2?",
    points: 10,
    description: "is 1+1=2?",
    options: ["True", "False"],
    answer: "True",
    student_answer: "",
  },
  {
    _id: "102",
    quiz: "Q101",
    type: "MC",
    title: "1+1=?",
    points: 10,
    description: "what is 1+1=?",
    options: ["2", "3", "4", "5"],
    answer: "2",
    student_answer: "",
  },
  {
    _id: "103",
    quiz: "Q102",
    type: "TF",
    title: "10+10=2?",
    points: 10,
    description: "is 1+1=2?",
    options: ["True", "False"],
    answer: "True",
    student_answer: "",
  },
  {
    _id: "104",
    quiz: "Q102",
    type: "MC",
    title: "1+1=?",
    points: 10,
    description: "what is 10+10=?",
    options: ["20", "30", "40", "50"],
    answer: "20",
    student_answer: "",
  },
];
